site_name: 'CAT-Board'
repo_name: 'CAT-Board'
site_description: 'The CAT Board is a Raspberry Pi HAT with a Lattice iCE40HX FPGA.'
site_author: 'Dave Vandenbout'
site_favicon: 'readthedocs/xess.ico'
copyright: '(c) 2015-2021 by Dave Vandenbout.'

pages:
- 'Introduction': 'index.md'
- 'Installation': 'installation.md'
- 'Usage': 'usage.md'
- 'License': 'licenses.md'
- 'History': 'history.md'
- 'Authors': 'authors.md'
- 'Contributing': 'contributing.md'

theme: 'readthedocs'
docs_dir: 'docs/readthedocs'
site_dir: 'site'
